sqitch add 1.init -n "Création des tables"
sqitch add 2.3fn -n "Adaptation à la 3e forme normale"
sqitch add 3.crud_functions -n "Création des fonction CRUD"
sqitch add 4.update_function_invoice -n "ajout du coalesce sur la date de paiement"
sqitch add 5.invoice_details -n "Création de la view pour les factures"
sqitch add 6.invoice_recap -n "Création de la view pour les factures avec des sous requêtes"
sqitch add 7.sales -n "Création d'une fonction pour les stats de ventes"
sqitch add 8.packed_invoice -n "Création d'une fonction pour le contenu d'une commande"
sqitch add 9.add_invoice -n "Création d'une fonction ajouter une facture"